from controllers.datagrabber import Harvester, Forecaster
import json

harvest_users = json.loads(
                    """{
                        "users": [
                            {
                                "id": 1111111,
                                "first_name": "John",
                                "last_name": "Doe",
                                "email": "john.doe@imatest.net",
                                "telephone": "",
                                "timezone": "Central Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": false,
                                "is_admin": false,
                                "is_project_manager": false,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2018-07-05T22:01:48Z",
                                "updated_at": "2018-07-16T17:56:10Z",
                                "default_hourly_rate": null,
                                "cost_rate": null,
                                "roles": [
                                    "Technology"
                                ],
                                "avatar_url": "https://yahoo.com"
                            },
                            {
                                "id": 2222222,
                                "first_name": "CJ",
                                "last_name": "Designerperson",
                                "email": "cjd@imatest.net",
                                "telephone": "",
                                "timezone": "Central Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": false,
                                "is_admin": false,
                                "is_project_manager": false,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2018-05-01T20:27:01Z",
                                "updated_at": "2018-07-16T13:30:50Z",
                                "default_hourly_rate": null,
                                "cost_rate": null,
                                "roles": [
                                    "Design (Ops)"
                                ],
                                "avatar_url": "https://yahoo.com"
                            },
                            {
                                "id": 1974747,
                                "first_name": "Chris",
                                "last_name": "Purney",
                                "email": "chris.purney@revunit.com",
                                "telephone": "",
                                "timezone": "Pacific Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": true,
                                "is_admin": false,
                                "is_project_manager": false,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2018-01-30T00:42:50Z",
                                "updated_at": "2018-07-17T16:57:28Z",
                                "default_hourly_rate": 100,
                                "cost_rate": 50,
                                "roles": [
                                    "Contractor",
                                    "Product"
                                ],
                                "avatar_url": "https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/001/974/747/normal.jpg?1517332030"
                            },
                            {
                                "id": 1973591,
                                "first_name": "Michael",
                                "last_name": "Pacheco",
                                "email": "michael.pacheco@revunit.com",
                                "telephone": "",
                                "timezone": "Central Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": false,
                                "is_admin": false,
                                "is_project_manager": false,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2018-01-29T20:29:53Z",
                                "updated_at": "2018-07-15T20:45:11Z",
                                "default_hourly_rate": null,
                                "cost_rate": null,
                                "roles": [
                                    "Dev",
                                    "Technology"
                                ],
                                "avatar_url": "https://cache.harvestapp.com/assets/profile_images/cornell_clock_tower.png?1517257793"
                            },
                            {
                                "id": 1946469,
                                "first_name": "Ryan",
                                "last_name": "Atkinson",
                                "email": "ryan.atkinson@revunit.com",
                                "telephone": "",
                                "timezone": "Central Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": true,
                                "is_admin": false,
                                "is_project_manager": false,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2018-01-04T21:50:22Z",
                                "updated_at": "2018-07-16T15:03:48Z",
                                "default_hourly_rate": null,
                                "cost_rate": 62.5,
                                "roles": [
                                    "Contractor",
                                    "Product"
                                ],
                                "avatar_url": "https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/001/946/469/normal.jpeg?1515104738"
                            },
                            {
                                "id": 1938830,
                                "first_name": "Colin",
                                "last_name": "Shaw",
                                "email": "colin@revunit.com",
                                "telephone": "",
                                "timezone": "Central Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": false,
                                "is_admin": false,
                                "is_project_manager": true,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2017-12-27T04:41:43Z",
                                "updated_at": "2018-07-16T21:20:22Z",
                                "default_hourly_rate": 214,
                                "cost_rate": null,
                                "roles": [
                                    "AR",
                                    "EmergingTech",
                                    "Full-Time",
                                    "ML Team"
                                ],
                                "avatar_url": "https://cache.harvestapp.com/assets/profile_images/big_ben.png?1514349703"
                            },
                            {
                                "id": 1937548,
                                "first_name": "Chris",
                                "last_name": "Warren",
                                "email": "chris@thechriswarren.net",
                                "telephone": "",
                                "timezone": "Central Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": true,
                                "is_admin": false,
                                "is_project_manager": false,
                                "can_see_rates": false,
                                "can_create_projects": false,
                                "can_create_invoices": false,
                                "is_active": true,
                                "created_at": "2017-12-22T15:35:46Z",
                                "updated_at": "2018-07-16T19:09:51Z",
                                "default_hourly_rate": 180,
                                "cost_rate": 100,
                                "roles": [
                                    "Boost",
                                    "Contractor",
                                    "Strategy"
                                ],
                                "avatar_url": "https://cache.harvestapp.com/assets/profile_images/allen_bradley_clock_tower.png?1513956946"
                            },
                            {
                                "id": 1567767,
                                "first_name": "Chaz",
                                "last_name": "Gugino",
                                "email": "chaz.gugino@revunit.com",
                                "telephone": "",
                                "timezone": "Pacific Time (US & Canada)",
                                "weekly_capacity": 144000,
                                "has_access_to_all_future_projects": false,
                                "is_contractor": false,
                                "is_admin": true,
                                "is_project_manager": true,
                                "can_see_rates": true,
                                "can_create_projects": true,
                                "can_create_invoices": true,
                                "is_active": true,
                                "created_at": "2017-04-01T13:22:31Z",
                                "updated_at": "2018-07-16T16:17:49Z",
                                "default_hourly_rate": null,
                                "cost_rate": null,
                                "roles": [
                                    "Billable",
                                    "NV",
                                    "PO",
                                    "Product",
                                    "Product Owner",
                                    "product_west",
                                    "zappos"
                                ],
                                "avatar_url": "https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/001/567/767/normal.jpg?1491186041"
                            }
                        ],
                        "per_page": 100,
                        "total_pages": 1,
                        "total_entries": 8,
                        "next_page": null,
                        "previous_page": null,
                        "page": 1,
                        "links": {
                            "first": null,
                            "next": null,
                            "previous": null,
                            "last": null
                        }
                    }"""
                    )

print(users)